sonar.projectKey=pipettentool-experiment
sonar.projectName=Pipettentool Experiment
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/__pycache__/**
